const ClassroomActionTypes = {
    'CREATE_CLASSROOM_START': 'CREATE_CLASSROOM_START',
    'CREATE_CLASSROOM_SUCCESS': 'CREATE_CLASSROOM_SUCCESS',
    'CREATE_CLASSROOM_FAILURE': 'CREATE_CLASSROOM_FAILURE',
    'JOIN_CLASSROOM_START': 'JOIN_CLASSROOM_START',
    'JOIN_CLASSROOM_SUCCESS': 'JOIN_CLASSROOM_SUCCESS',
    'JOIN_CLASSROOM_FAILURE': 'JOIN_CLASSROOM_FAILURE',
    'CREATING_CLASSROOM': 'CREATING_CLASSROOM',
    'JOINING_CLASSROOM': 'JOINING_CLASSROOM',
    'STORE_USER_CLASSROOMS': 'STORE_USER_CLASSROOMS'
}

export default ClassroomActionTypes;